/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poscofmat;

import javax.swing.ImageIcon;

/**
 *
 * @author samsung
 */
public class reports extends javax.swing.JFrame {

    /**
     * Creates new form reports
     */
    public reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JLabel();
        logOut = new javax.swing.JLabel();
        sale = new javax.swing.JLabel();
        order = new javax.swing.JLabel();
        report = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        panelOne = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelTwo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelThree = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelFour = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        buttonOne = new javax.swing.JButton();
        buttonTwo = new javax.swing.JButton();
        buttonThree = new javax.swing.JButton();
        buttonFour = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 0, 40, 30));

        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutMouseExited(evt);
            }
        });
        getContentPane().add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 55, 131, 43));

        sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saleMouseExited(evt);
            }
        });
        getContentPane().add(sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 48, 130, 56));

        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderMouseExited(evt);
            }
        });
        getContentPane().add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 48, 130, 56));

        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportMouseExited(evt);
            }
        });
        getContentPane().add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 48, 130, 56));

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Daily Reports");
        panelOne.add(jLabel2);

        mainPanel.add(panelOne, "card2");

        jLabel3.setText("Weekly Reports");
        panelTwo.add(jLabel3);

        mainPanel.add(panelTwo, "card3");

        jLabel4.setText("Monthly Reports");
        panelThree.add(jLabel4);

        mainPanel.add(panelThree, "card4");

        jLabel5.setText("Yearly Reports");
        panelFour.add(jLabel5);

        mainPanel.add(panelFour, "card5");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 870, 620));

        buttonOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonReports/1.png"))); // NOI18N
        buttonOne.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonReports/1hvr.png"))); // NOI18N
        buttonOne.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonReports/1hvr.png"))); // NOI18N
        buttonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 135, 39));

        buttonTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonReports/2.png"))); // NOI18N
        buttonTwo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonReports/2hvr.png"))); // NOI18N
        buttonTwo.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonReports/2hvr.png"))); // NOI18N
        buttonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, 135, 39));

        buttonThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonReports/3.png"))); // NOI18N
        buttonThree.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonReports/3hvr.png"))); // NOI18N
        buttonThree.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonReports/3hvr.png"))); // NOI18N
        buttonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThreeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, 135, 39));

        buttonFour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonReports/4.png"))); // NOI18N
        buttonFour.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonReports/4hvr.png"))); // NOI18N
        buttonFour.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonReports/4hvr.png"))); // NOI18N
        buttonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFourActionPerformed(evt);
            }
        });
        getContentPane().add(buttonFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 249, 135, 39));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/nav bar - buttons-log out.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/button/clsehvr.png"));
        close.setIcon(ico);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/button/clsehvr.png"));
        close.setIcon(null);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void logOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/logouthvr.png"));
        logOut.setIcon(ico);
    }//GEN-LAST:event_logOutMouseEntered

    private void logOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/logouthvr.png"));
        logOut.setIcon(null);
    }//GEN-LAST:event_logOutMouseExited

    private void saleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/slshvr.png"));
        sale.setIcon(ico);
    }//GEN-LAST:event_saleMouseEntered

    private void saleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/slshvr.png"));
        sale.setIcon(null);
    }//GEN-LAST:event_saleMouseExited

    private void orderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/ordrhvr.png"));
        order.setIcon(ico);
    }//GEN-LAST:event_orderMouseEntered

    private void orderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/ordrhvr.png"));
        order.setIcon(null);
    }//GEN-LAST:event_orderMouseExited

    private void reportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/rprthvr.png"));
        report.setIcon(ico);
    }//GEN-LAST:event_reportMouseEntered

    private void reportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/rprthvr.png"));
        report.setIcon(null);
    }//GEN-LAST:event_reportMouseExited

    private void buttonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOneActionPerformed
        mainPanel.removeAll();
        mainPanel.add(panelOne);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_buttonOneActionPerformed

    private void buttonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwoActionPerformed
        mainPanel.removeAll();
        mainPanel.add(panelTwo);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_buttonTwoActionPerformed

    private void buttonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThreeActionPerformed
        mainPanel.removeAll();
        mainPanel.add(panelThree);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_buttonThreeActionPerformed

    private void buttonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFourActionPerformed
        mainPanel.removeAll();
        mainPanel.add(panelFour);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_buttonFourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFour;
    private javax.swing.JButton buttonOne;
    private javax.swing.JButton buttonThree;
    private javax.swing.JButton buttonTwo;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel logOut;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel order;
    private javax.swing.JPanel panelFour;
    private javax.swing.JPanel panelOne;
    private javax.swing.JPanel panelThree;
    private javax.swing.JPanel panelTwo;
    private javax.swing.JLabel report;
    private javax.swing.JLabel sale;
    // End of variables declaration//GEN-END:variables
}
