/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poscofmat;

import javax.swing.ImageIcon;

/**
 *
 * @author samsung
 */
public class salesOrder extends javax.swing.JFrame {

    /**
     * Creates new form salesOrder
     */
    public salesOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JLabel();
        logOut = new javax.swing.JLabel();
        sale = new javax.swing.JLabel();
        order = new javax.swing.JLabel();
        report = new javax.swing.JLabel();
        checkOut = new javax.swing.JLabel();
        zero = new javax.swing.JLabel();
        dblZero = new javax.swing.JLabel();
        dat = new javax.swing.JLabel();
        one = new javax.swing.JLabel();
        two = new javax.swing.JLabel();
        three = new javax.swing.JLabel();
        four = new javax.swing.JLabel();
        five = new javax.swing.JLabel();
        six = new javax.swing.JLabel();
        seven = new javax.swing.JLabel();
        eigth = new javax.swing.JLabel();
        nine = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 0, 40, 30));

        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutMouseExited(evt);
            }
        });
        getContentPane().add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 55, 131, 43));

        sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saleMouseExited(evt);
            }
        });
        getContentPane().add(sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 48, 130, 56));

        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderMouseExited(evt);
            }
        });
        getContentPane().add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 48, 130, 56));

        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportMouseExited(evt);
            }
        });
        getContentPane().add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 48, 130, 56));

        checkOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkOutMouseExited(evt);
            }
        });
        getContentPane().add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 622, 319, 127));

        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                zeroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                zeroMouseExited(evt);
            }
        });
        getContentPane().add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 480, 100, 100));

        dblZero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dblZeroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dblZeroMouseExited(evt);
            }
        });
        getContentPane().add(dblZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 480, 100, 100));

        dat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datMouseExited(evt);
            }
        });
        getContentPane().add(dat, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 480, 100, 100));

        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                oneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oneMouseExited(evt);
            }
        });
        getContentPane().add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 375, 100, 100));

        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                twoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                twoMouseExited(evt);
            }
        });
        getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 375, 100, 100));

        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                threeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                threeMouseExited(evt);
            }
        });
        getContentPane().add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 375, 100, 100));

        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fourMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fourMouseExited(evt);
            }
        });
        getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 270, 100, 100));

        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fiveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fiveMouseExited(evt);
            }
        });
        getContentPane().add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 270, 100, 100));

        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sixMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sixMouseExited(evt);
            }
        });
        getContentPane().add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 270, 100, 100));

        seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sevenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sevenMouseExited(evt);
            }
        });
        getContentPane().add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 166, 100, 100));

        eigth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eigthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eigthMouseExited(evt);
            }
        });
        getContentPane().add(eigth, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 166, 100, 100));

        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nineMouseExited(evt);
            }
        });
        getContentPane().add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 166, 100, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/2.2-sell-2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/button/clsehvr.png"));
        close.setIcon(ico);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/button/clsehvr.png"));
        close.setIcon(null);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
       System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void logOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/logouthvr.png"));
        logOut.setIcon(ico);
    }//GEN-LAST:event_logOutMouseEntered

    private void logOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/logouthvr.png"));
        logOut.setIcon(null);
    }//GEN-LAST:event_logOutMouseExited

    private void saleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/slshvr.png"));
        sale.setIcon(ico);
    }//GEN-LAST:event_saleMouseEntered

    private void saleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/slshvr.png"));
        sale.setIcon(null);
    }//GEN-LAST:event_saleMouseExited

    private void orderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/ordrhvr.png"));
        order.setIcon(ico);
    }//GEN-LAST:event_orderMouseEntered

    private void orderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/ordrhvr.png"));
        order.setIcon(null);
    }//GEN-LAST:event_orderMouseExited

    private void reportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/rprthvr.png"));
        report.setIcon(ico);
    }//GEN-LAST:event_reportMouseEntered

    private void reportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNavBar/rprthvr.png"));
        report.setIcon(null);
    }//GEN-LAST:event_reportMouseExited

    private void checkOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/button/chckouthvr.png"));
        checkOut.setIcon(ico);
    }//GEN-LAST:event_checkOutMouseEntered

    private void checkOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/button/chckouthvr.png"));
        checkOut.setIcon(null);
    }//GEN-LAST:event_checkOutMouseExited

    private void zeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/0hvr.png"));
        zero.setIcon(ico);
    }//GEN-LAST:event_zeroMouseEntered

    private void zeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/0hvr.png"));
        zero.setIcon(null);
    }//GEN-LAST:event_zeroMouseExited

    private void dblZeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dblZeroMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/00hvr.png"));
        dblZero.setIcon(ico);
    }//GEN-LAST:event_dblZeroMouseEntered

    private void dblZeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dblZeroMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/00hvr.png"));
        dblZero.setIcon(null);
    }//GEN-LAST:event_dblZeroMouseExited

    private void datMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/dathvr.png"));
        dat.setIcon(ico);
    }//GEN-LAST:event_datMouseEntered

    private void datMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/dathvr.png"));
        dat.setIcon(null);
    }//GEN-LAST:event_datMouseExited

    private void oneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/1hvr.png"));
        one.setIcon(ico);
    }//GEN-LAST:event_oneMouseEntered

    private void oneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/1hvr.png"));
        one.setIcon(null);
    }//GEN-LAST:event_oneMouseExited

    private void twoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/2hvr.png"));
        two.setIcon(ico);
    }//GEN-LAST:event_twoMouseEntered

    private void twoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/2hvr.png"));
        two.setIcon(null);
    }//GEN-LAST:event_twoMouseExited

    private void threeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/3hvr.png"));
        three.setIcon(ico);
    }//GEN-LAST:event_threeMouseEntered

    private void threeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/3hvr.png"));
        three.setIcon(null);
    }//GEN-LAST:event_threeMouseExited

    private void fourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/4hvr.png"));
        four.setIcon(ico);
    }//GEN-LAST:event_fourMouseEntered

    private void fourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/4hvr.png"));
        four.setIcon(null);
    }//GEN-LAST:event_fourMouseExited

    private void fiveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/5hvr.png"));
        five.setIcon(ico);
    }//GEN-LAST:event_fiveMouseEntered

    private void fiveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/5hvr.png"));
        five.setIcon(null);
    }//GEN-LAST:event_fiveMouseExited

    private void sixMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/6hvr.png"));
        six.setIcon(ico);
    }//GEN-LAST:event_sixMouseEntered

    private void sixMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/6hvr.png"));
        six.setIcon(null);
    }//GEN-LAST:event_sixMouseExited

    private void sevenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/7hvr.png"));
        seven.setIcon(ico);
    }//GEN-LAST:event_sevenMouseEntered

    private void sevenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/7hvr.png"));
        seven.setIcon(null);
    }//GEN-LAST:event_sevenMouseExited

    private void eigthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eigthMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/8hvr.png"));
        eigth.setIcon(ico);
    }//GEN-LAST:event_eigthMouseEntered

    private void eigthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eigthMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/8hvr.png"));
        eigth.setIcon(null);
    }//GEN-LAST:event_eigthMouseExited

    private void nineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttonNumPad/9hvr.png"));
        nine.setIcon(ico);
    }//GEN-LAST:event_nineMouseEntered

    private void nineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseExited
        nine.setIcon(null);
    }//GEN-LAST:event_nineMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salesOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkOut;
    private javax.swing.JLabel close;
    private javax.swing.JLabel dat;
    private javax.swing.JLabel dblZero;
    private javax.swing.JLabel eigth;
    private javax.swing.JLabel five;
    private javax.swing.JLabel four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logOut;
    private javax.swing.JLabel nine;
    private javax.swing.JLabel one;
    private javax.swing.JLabel order;
    private javax.swing.JLabel report;
    private javax.swing.JLabel sale;
    private javax.swing.JLabel seven;
    private javax.swing.JLabel six;
    private javax.swing.JLabel three;
    private javax.swing.JLabel two;
    private javax.swing.JLabel zero;
    // End of variables declaration//GEN-END:variables
}
